### ISSUE TITLE
Default settings fail in new regions due to outdated signature_version default.

### ISSUE THREAD

**Issue by markstos** [mrallen1/net-amazon-ec2#52]
The undocumented default signature_version is "2". 

The leads to code that runs in some regions but not others, which could lead to surprising or unexpected failures when identical code is deployed in multiple regions. 

This official AWS page documents which regions don't support Signature Version 2. The failing defaults causes downstream projects like `ec2-consistent-snapshot` to also fail when deployed in new regions.

Reference: https://github.com/alestic/ec2-consistent-snapshot/issues/87

**Comment by mrallen1** [comment]
I set the default to 4 in 0.32 which I just released to CPAN. Thanks for the ticket.
