### ISSUE TITLE
example code not working

### ISSUE THREAD

**Issue by taktus** [mrallen1/net-amazon-ec2#55]
describe_instances throws error:

_Attribute (code) does not pass the type constraint because: Validation failed for 'Int|Str' with value undef at constructor Net::Amazon::EC2::StateReason::new (defined at /usr/local/share/perl/5.22.1/Net/Amazon/EC2/StateReason.pm line 31) line 31
	Net::Amazon::EC2::StateReason::new('Net::Amazon::EC2::StateReason', 'code', undef, 'message', undef) called at /usr/local/share/perl/5.22.1/Net/Amazon/EC2.pm line 2098_

**Comment by mrallen1** [comment]
Can you please tell me what AMI you're using in the example code?

**Comment by taktus** [comment]
tested on starndard aaws ubuntu 12.04, 14.04 and 16.04 Lts



W dniu śr., 23.08.2017 o 15:48 Mark Allen <notifications@github.com>
napisał(a):

**Comment by mrallen1** [comment]
The synopsis has an ami of `ami-XXXXXXX` which is totally invalid. So did you literally copy and paste the synopsis and run it or did you use your own AMI?

**Comment by mrallen1** [comment]
Going to close this issue for now. Please open a new one if needed.
