### ISSUE TITLE
M::I modules missing from tarball

### ISSUE THREAD

**Issue by fschlich** [mrallen1/net-amazon-ec2#56]
Hi, I think your CPAN tarball misses 4 M::I modules necessary for running 'perl Makefile.PL':

 inc/Module/Install/Can.pm
 inc/Module/Install/Fetch.pm
 inc/Module/Install/Win32.pm
 inc/Module/Install/WriteAll.pm

Perhaps you forgot to run 'make dist' or some such?

**Comment by mrallen1** [comment]
I'll check. Thanks for the note.

**Comment by mrallen1** [comment]
Hi, sorry for the trouble. I've uploaded 0.34 to CPAN with the missing files. I'm not sure why they weren't included in 0.33
