### ISSUE TITLE
Cannot install 0.33 with cpanm

### ISSUE THREAD

**Issue by apptaro** [mrallen1/net-amazon-ec2#58]
I'm using CentOS 7. I can install 0.32 but not 0.33 with cpanm. See below.

> [09:57:10 centos@server.aflat.jp deploytmp]$ sudo yum update
> Loaded plugins: fastestmirror
> Loading mirror speeds from cached hostfile
>  * base: ftp.iij.ad.jp
>  * extras: ftp.iij.ad.jp
>  * updates: ftp.iij.ad.jp
> No packages marked for update
> 
> [09:57:15 centos@server.aflat.jp deploytmp]$ sudo cpanm http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.32.tar.gz
> --> Working on http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.32.tar.gz
> Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.32.tar.gz ... OK
> Configuring Net-Amazon-EC2-0.30_1 ... OK
> Building and testing Net-Amazon-EC2-0.30_1 ... OK
> Successfully installed Net-Amazon-EC2-0.30_1
> 1 distribution installed
> 
> [09:57:19 centos@server.aflat.jp deploytmp]$ sudo cpanm http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.33.tar.gz
> --> Working on http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.33.tar.gz
> Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.33.tar.gz ... OK
> Configuring Net-Amazon-EC2-0.33 ... N/A
> ! Configure failed for Net-Amazon-EC2-0.33. See /root/.cpanm/work/1514422640.24102/build.log for details.
> 
> [09:57:20 centos@server.aflat.jp deploytmp]$ sudo cat /root/.cpanm/work/1514422640.24102/build.log
> cpanm (App::cpanminus) 1.6922 on perl 5.016003 built for x86_64-linux-thread-multi
> Work directory is /root/.cpanm/work/1514422640.24102
> You have make /bin/make
> You have LWP 6.05
> You have /bin/tar: tar (GNU tar) 1.26
> Copyright (C) 2011 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by John Gilmore and Jay Fenlason.
> You have /bin/unzip
> --> Working on http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.33.tar.gz
> Fetching http://search.cpan.org/CPAN/authors/id/M/MA/MALLEN/Net-Amazon-EC2-0.33.tar.gz
> -> OK
> Unpacking Net-Amazon-EC2-0.33.tar.gz
> Entering Net-Amazon-EC2-0.33
> Checking configure dependencies from META.yml
> Checking if you have ExtUtils::MakeMaker 6.36 ... Yes (6.68)
> Configuring Net-Amazon-EC2-0.33
> Running Makefile.PL
> Bareword "WriteAll" not allowed while "strict subs" in use at Makefile.PL line 28.
> Execution of Makefile.PL aborted due to compilation errors.
> -> N/A
> -> FAIL Configure failed for Net-Amazon-EC2-0.33. See /root/.cpanm/work/1514422640.24102/build.log for details.
> [09:57:29 centos@server.aflat.jp deploytmp]$
>

**Comment by mrallen1** [comment]
Just uploaded 0.34. Please try that. Open a new ticket if you're still having trouble.
